version: "3.9"

services:
  user-service:
    build:
      context: ./user-service
    container_name: user-service
    expose:
      - "3001"
    restart: unless-stopped

  post-service:
    build:
      context: ./post-service
    container_name: post-service
    expose:
      - "3002"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: api-gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - user-service
      - post-service
    restart: unless-stopped
