version: "3.9"

services:
  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "3001:3001"
    restart: unless-stopped

  post-service:
    build:
      context: ./post-service
    container_name: post-service
    ports:
      - "3002:3002"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service
      - post-service
    restart: unless-stopped
